myblog/blueprints/admin.py
from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint
from flask_login import login_required, current_user

from myblog.extensions import db
from myblog.forms import SettingForm, PostForm, CategoryForm, LinkForm, SkillForm
from myblog.models import Post, Category, Comment, Link, Skill
from myblog.utils import redirect_back


admin_bp = Blueprint("admin",__name__)



@admin_bp.before_request
@login_required
def login_protect():
    pass


# post
@admin_bp.route("/post/new",methods=["GET","POST"])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category)
        db.session.add(post)
        db.session.commit()
        flash("post created", "success")
        return redirect(url_for("blog.show_post", post_id=post.id))
    return render_template("admin/new_post.html", form=form)


@admin_bp.route("/post/edit/<int:post_id>",methods=["GET","POST"])
def edit_post(post_id):
    post = Post.query.get(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        db.session.commit()
        flash("edit success!", "success")
        return redirect(url_for("blog.show_post", post_id=post.id))
    form.category.data = post.category_id
    form.title.data = post.title
    form.body.data = post.body
    return render_template("admin/edit_post.html", form=form)


@admin_bp.route("/post/delete/<int:post_id>", methods=["POST"])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for("blog.index"))


@admin_bp.route("/manage_post", methods=["GET", "POST"])
def manage_post():
    categories = Category.query.all()
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config.get("MYBLOG_POST_PER_PAGE")
    filter_rule = request.args.get("filter", "all")  #  all category
    if filter_rule == "all":
        filtered_posts = Post.query.order_by(Post.timestamp.desc())
    else:
        filtered_posts = db.session.query(Post).join(Category).filter(Category.name == filter_rule).order_by(Post.timestamp.desc())
    pagination = filtered_posts.paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template("admin/manage_post.html", pagination=pagination, posts=posts, categories=categories)


# comment
@admin_bp.route("/post/set_comment/<int:post_id>", methods=["POST"])
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment :
        post.can_comment = False
        flash("Comment disabled", "success")
    else:
        post.can_comment = True
        flash("Comment enabled", "success")
    db.session.commit()
    return redirect_back()


@admin_bp.route("/post/delete_comment/<int:comment_id>", methods=["POST"])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    return redirect_back()


@admin_bp.route("/manage_comment", methods=["GET","POST"])
def manage_comment():
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config.get("MYBLOG_COMMENT_PER_PAGE")
    filter_rule = request.args.get("filter", "all")  #  all unread admin
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False).order_by(Comment.timestamp.desc())
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True).order_by(Comment.timestamp.desc())
    else:
        filtered_comments = Comment.query.order_by(Comment.timestamp.desc())

    pagination = filtered_comments.paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template("admin/manage_comment.html", pagination=pagination, comments=comments)


@admin_bp.route("/approve_comment/<int:comment_id>", methods=["POST"])
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    return redirect_back()


# category
@admin_bp.route("/new_category", methods=["GET","POST"])
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for("blog.index"))
    return render_template("/admin/new_category.html", form=form)


@admin_bp.route("/manage_category")
def manage_category():
    categories = Category.query.all()
    return render_template("admin/manage_category.html", categories=categories)


@admin_bp.route("/edit_category/<int:category_id>", methods=["GET","POST"])
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = CategoryForm()
    if category.id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect_back()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.', 'success')
        return redirect(url_for('.manage_category'))

    form.name.data = category.name
    return render_template("admin/edit_category.html", form=form)


@admin_bp.route("/delete_category/<int:category_id>", methods=["POST"])
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect_back()
    category.delete()
    return redirect_back()


# link
@admin_bp.route("/new_link", methods=["GET","POST"])
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        link = Link(name=form.name.data, url=form.url.data)
        db.session.add(link)
        db.session.commit()
        return redirect(url_for("blog.index"))
    return render_template("/admin/new_link.html", form=form)


@admin_bp.route("/manage_link", methods=["GET","POST"])
def manage_link():
    links = Link.query.all()
    return render_template("admin/manage_link.html", links=links)


@admin_bp.route("/edit_link/<int:link_id>", methods=["GET","POST"])
def edit_link(link_id):
    link = Link.query.get_or_404(link_id)
    form = LinkForm()
    if form.validate_on_submit():
        link.url = form.url.data
        link.name = form.name.data
        db.session.commit()
        return redirect_back()
    form.name.data = link.name
    form.url.data = link.url
    return render_template("admin/edit_link.html", form=form)

@admin_bp.route("/delete_link/<int:link_id>", methods=["POST"])
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    return redirect(url_for("admin.manage_link"))


#settings
@admin_bp.route("/settings", methods=["GET","POST"])
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)


#Skill
@admin_bp.route("/new_skill", methods=["GET","POST"])
def new_skill():
    form = SkillForm()
    if form.validate_on_submit():
        link = Skill(name=form.name.data)
        db.session.add(link)
        db.session.commit()
        return redirect(url_for("blog.index"))
    return render_template("/admin/new_skill.html", form=form)


@admin_bp.route("/manage_skill", methods=["GET","POST"])
def manage_skill():
    skills = Skill.query.all()
    return render_template("admin/manage_skill.html", skills=skills)


@admin_bp.route("/delete_skill/<int:skill_id>", methods=["POST"])
def delete_skill(skill_id):
    skill = Skill.query.get_or_404(skill_id)
    db.session.delete(skill)
    db.session.commit()
    return redirect(url_for("admin.manage_skill"))


@admin_bp.route("/edit_skill/<int:skill_id>", methods=["GET","POST"])
def edit_skill(skill_id):
    skill = Skill.query.get_or_404(skill_id)
    form = SkillForm()
    if form.validate_on_submit():
        skill.name = form.name.data
        db.session.commit()
        return redirect(url_for('blog.index'))
    form.name.data = skill.name
    return render_template("admin/edit_skill.html", form=form)

myblog/blueprints/blog.py
from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, abort, make_response
from flask_login import current_user
from myblog.emails import send_new_comment_email, send_new_reply_email
from myblog.extensions import db
from myblog.forms import CommentForm, AdminCommentForm
from myblog.models import Post, Category, Comment
from myblog.utils import redirect_back

blog_bp = Blueprint("blog", __name__)


@blog_bp.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["MYBLOG_MANAGE_POST_PER_PAGE"]
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template("blog/index.html", pagination=pagination, posts=posts)

@blog_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config["MYBLOG_MANAGE_POST_PER_PAGE"]
    pagination = Post.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template("blog/index.html", pagination=pagination, posts=results)

@blog_bp.route("/about")
def about():
    return render_template("blog/about.html")


@blog_bp.route("/category/<int:category_id>")
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["MYBLOG_MANAGE_POST_PER_PAGE"]
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template("blog/category.html", category=category, pagination=pagination, posts=posts)


@blog_bp.route("/post/<int:post_id>",methods=["GET","POST"])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get("page",1,type=int)
    per_page = current_app.config["MYBLOG_COMMENT_PER_PAGE"]
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(page,per_page=per_page)
    comments = pagination.items
    post.clicks += 1
    db.session.commit()

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config["MYBLOG_EMAIL"]
        form.site.data = url_for(".index")
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed
        )
        replied_id = request.args.get("reply")
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:
            flash("Comment published", "success")
        else:
            flash("Thanks, your comment will be published after reviewed.", "info")
            send_new_comment_email(post)
        return redirect(url_for(".show_post",post_id=post_id))
    return render_template("blog/post.html", post=post, pagination=pagination, form=form, comments=comments)


@blog_bp.route("/change_theme/<string:theme_name>")
def change_theme(theme_name):
    if theme_name not in current_app.config["MYBLOG_THEMES"].keys():
        abort(404)

    response = make_response(redirect_back())
    response.set_cookie("theme", theme_name, max_age=30*24*60*60)
    return response


@blog_bp.route("/post/reply/<comment_id>")
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash("Comment is disabled", "warning")
        return redirect(url_for("blog.show_post", post_id=comment.post.id))
    return redirect(url_for("blog.show_post", post_id=comment.post.id, reply=comment_id, author=comment.author) + "#comment-form")

myblog/templates/base.html
{% from "bootstrap/nav.html" import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>myblog</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'minty')) }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/default.css') }}" type="text/css">
	    <style>
    .Aclass{color:black;font-size:25px;}
</style>
    {% endblock head %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
    <a class="navbar-brand" href="/">Myblog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
           {{ render_nav_item('blog.index', 'Home') }}
            <form class="form-inline my-2 my-lg-0" action="{{ url_for('blog.search') }}">
                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="title, content"
                               required>
                        <button class="btn btn-light my-2 my-sm-0" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
        </ul>

        <ul class="nav navbar-nav navbar-right">
                    {{ render_nav_item('blog.about', 'about') }}
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                New <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_link') }}">Link</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_skill') }}">Skill</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Manage <span class="caret"></span>
                                {% if unread_comments %}
                                    <span class="badge badge-success">new</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_comment') }}">
                                    Comment
                                    {% if unread_comments %}
                                        <span class="badge badge-success">{{ unread_comments }}</span>
                                    {% endif %}
                                </a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_link') }}">Link</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_skill') }}">Skill</a>
                            </div>
                        </li>
                        {{ render_nav_item('admin.settings', 'Settings') }}
                        {% if current_user.is_authenticated %}
                            {{ render_nav_item('auth.logout', 'logout') }}
                        {% endif %}
                    {% else %}
                        {{ render_nav_item('auth.login', 'login') }}
                    {% endif %}
                </ul>

    </div>
</div>
</nav>
{% endblock nav %}
<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}
    {% block content %}{% endblock content %}
    {% block footer %}
    <footer>
    Lyh 2 u
　　</footer>
    {% endblock footer %}
</main>
{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-cn') }}
{#{% assets "main_js" %}#}
{#    <script type="text/javascript" src="{{ ASSET_URL }}"></script>#}
{#{% endassets %}#}
{% endblock scripts %}

</body>
</html>